default_stages: [commit]

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer

- repo: https://github.com/myint/autoflake
  rev: v1.4
  hooks:
  - id: autoflake
    args: [--remove-all-unused-imports]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910-1
  hooks:
  - id: mypy

- repo: local
  hooks:
  - id: pytest-unit-tests
    name: pytest unit tests
    entry: pytest
    args: [tests/]
    language: python
    types: [python]
    stages: [push]
    pass_filenames: false
  - id: pytest-integration-tests
    name: pytest integration tests
    entry: pytest
    args: [integrationtests/]
    language: python
    types: [python]
    stages: [push]
    pass_filenames: false
  - id: dvc-push
    name: dvc-push
    entry: poetry run dvc push
    types: [file]
    stages: [push]
    language: python
    pass_filenames: false

- repo: https://github.com/psf/black
  rev: 21.12b0
  hooks:
  - id: black
    args: [-l, '118']

- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.20.2
  hooks:
  - id: commitizen
    stages: [commit-msg]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.2.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix]

- repo: meta
  hooks:
  - id: check-useless-excludes

- repo: https://github.com/hadolint/hadolint
  rev: v2.8.0
  hooks:
  - id: hadolint-docker
    args: [-t, warning]

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.30.0
  hooks:
  - id: markdownlint-fix

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.5.1
  hooks:
  - id: prettier
    types_or: [css, javascript, json]
